name: "microsoft-surface-common cache host"
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
jobs:
  cache:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: cachix/install-nix-action@v27
      with:
        nix_path: nixpkgs=channel:nixos-unstable
        github_access_token: ${{ secrets.GITHUB_TOKEN }}
    - uses: cachix/cachix-action@v14
      with:
        name: dessera-nix
        authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
    - run: nix build .#microsoft-surface-common-cache-host